
#============================================================
# Copyright (c) 2019-2021 iplcdn <https://iplcdn.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/MuaCat/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#============================================================

name: Remove old artifacts

on:
  schedule:
    - cron: 0 14 * * fri
  #  每周五晚上 22 点自动编译。
  #  watch:
  #    types: started
  #  - cron: 0 8 */5 * *
  #  - cron: 0 22,14 * * *
  #  每天运行两次，在上午 6 点和晚上 22 点。
  #  - cron: 0 20 * * fri
  #  每周五凌晨四点自动编译。
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
    #- name: Remove old artifacts
    #  uses: c-hive/gha-remove-artifacts@v1
    #  with:
    #     age: '1 month'
         #Optional inputs
         #skip-tags: true
         #skip-recent: 5
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 14
        keep_minimum_runs: 10

